### ISSUE TITLE
Dimensions that use parameters...

### ISSUE THREAD

**Issue by DylanBaker** [spectacles-ci/spectacles#12]
Some dimensions reference parameters. When we try to query these dimensions without setting the parameter, we may receive SQL errors because a field reference is missing.

Possible solutions:

* Omit those dimensions?
* Set the parameters?

**Comment by DylanBaker** [comment]
Changing this from `bug` to `enhancement` as the bug component can be managed by the `-- spectacles: ignore` functionality. #58

**Comment by agile** [comment]
heya, just wanted to confirm if this was closed because we can ignore dimensions with parameters, or maybe a work-around exists? Sorry, haven't been keeping track of all the great things ya'll have doing here and had a dimension like this trigger some failures after updating from 1.2.1 to 2.2.0, not sure how it was _not_ failing before.

**Comment by DylanBaker** [comment]
Hey @agile. The two solutions that most people are using here is to either ignore the affected dimensions, or to set default values on all parameters so that those get passed to the affected dimensions and can be tested.

That said, I'm not aware of anything that would have changed between those versions that would have not caused an error before and would have now. Are you able to retry with version 1.2.1 and see what query is being run against that dimension?
