### ISSUE TITLE
Assert Command Hangs

### ISSUE THREAD

**Issue by msandt3** [spectacles-ci/spectacles#160]
Hey Y'all,

Running into some strange behavior now that we've got this completely rolled into our CI process. It only seems to be an issue with the `assert` command. The behavior we're noticing is that in CI, we kick off a build of a branch. We run our assert command on the models in question. These take a bit to run, but we can see them being executed in the Looker Queries tab. I've redacted some sensitive information but you can see the overall picture below:

<img width="1477" alt="Screen Shot 2020-02-06 at 10 40 44 AM" src="https://user-images.githubusercontent.com/2781585/74063747-2665ac00-49bf-11ea-9636-1ed393287079.png">

In the above case they all succeed - great!

However, in our CI console, we don't seem to receive any output from the command so it'll just sit there and hang until our CI process decides to kill it. 

<img width="1792" alt="Screen Shot 2020-02-07 at 3 27 20 PM" src="https://user-images.githubusercontent.com/2781585/74063925-83616200-49bf-11ea-9586-e10e3afbf182.png">

Most of the time, you can simply stop it and re-run the build. Looker seems to cache the test results from the previous run so everything gets executed in a manner of a minute or so. 

Any chance this is a known issue or a workaround is available? I'm happy to run some things locally to help diagnose.

**Comment by joshtemple** [comment]
Hey Mike! Any chance you could pass the `--verbose` flag in your CI job or local reproduction so we can see debug level logging? That might help us understand what request to the API is getting stuck.

Does this ever happen when you re-run with cached results? Or does it only happen when you would guess the results are not cached?

**Comment by msandt3** [comment]
@joshtemple - I'll try with the `--verbose` flag and report back. It only seems to happen when the results are not cached.

**Comment by msandt3** [comment]
@joshtemple - reporting back here. The only logs I'm getting back in verbose mode are up to this point https://github.com/spectacles-ci/spectacles/blob/00094dc9d145d51348886a906754f1830017efa4/spectacles/client.py#L233

I did confirm for this run that it made it through all of the LookML Test queries successfully. So not sure what's going on here. My assumption is that it could have been an issue keeping the connection alive but it seems like that's alleviated using sessions (https://2.python-requests.org/en/v1.1.0/user/advanced/). Not entirely sure what's going on here at this point.



See the screencap below: 
<img width="1583" alt="Screen Shot 2020-02-11 at 2 51 28 PM" src="https://user-images.githubusercontent.com/2781585/74278858-dc930380-4ce7-11ea-9236-496581935fb2.png">

Happy to run any additional steps you need from my end.

**Comment by joshtemple** [comment]
Thanks for looking into this more. It's possible that this is a Looker API issue where the connection is not being closed. Here's an idea for how you could confirm that, adding this code within `logger.py` with the other logging config code:

```
requests_logger = logging.getLogger("requests.packages.urllib3")
requests_logger.setLevel(logging.DEBUG)
requests_logger.propagate = True
```

This should emit logging messages for the actual connections, so you could see if something is hanging.

As far as fixing this goes, we could add a timeout, catch the timeout exception, and retry, but that would re-run the tests which isn't ideal.

I'm going to tag this as a Looker API issue for now until we can confirm otherwise with logging. If you don't mind, could you submit a ticket to their support to investigate and reference this issue? Probably best for you to submit since you have a working reproduction.
