### ISSUE TITLE
Add support for GCP-hosted Looker instances

### ISSUE THREAD

**Issue by tpakeman** [spectacles-ci/spectacles#162]
It is now possible to host Looker on GCP using Kubernetes.

Kubernetes can only route requests to services based on host name and url path, not port number, and so API calls to GCP-hosted instances must not contain a port number.

It would be great to allow a port override via the CLI or config file (i.e. omit the port from the base url entirely if the config file has an empty string for the port).

**Comment by MartinGuindon** [comment]
GCP-hosted instances can be used by specifying the port number in the CLI, eg : `spectacles connect --config-file config.yaml --port 443`.

However I think Spectacles should handle this automatically based on the URL structure. Any *.cloud.looker.com instances are hosted on GCP and therefore their default port is 443 instead of 19999.

**Comment by joshtemple** [comment]
I’d be happy to make that change. I was struggling with the right way to
solve it and that makes more sense than anything I’ve come up with so far.
