### ISSUE TITLE
Return dangling content validation errors

### ISSUE THREAD

**Issue by joshtemple** [spectacles-ci/spectacles#240]
It's possible that the content validator could return content errors that are no longer associated with an existing explore. When this happens, Spectacles could display the errors anyway or display a message asking the user to run validation without selecting or excluding anything to see the errors.

It would be helpful to reproduce the API response in this case and decide how to handle this edge case.

**Comment by DylanBaker** [comment]
Adding a note that we now know that models are globally unique, so we should be able to assign a dangling error to its model, at the very least.

**Comment by sadir** [comment]
@DylanBaker - I ran into this today, any plans for this issue?

**Comment by DylanBaker** [comment]
Hey @sadir. I don't think it is something we have immediate plans to implement, though we would be very open to a contribution. 

I see a couple issues that I don't have good ideas on how to solve:
* If a model gets renamed, there's really nothing we can attach it to. I think in this scenario we might not have any options.
* If an explore gets renamed, we need to find a way to differentiate between an explore isn't in the LookML tree we build because it was excluded and those where the explore doens't exist at all anymore. I think one option here would be to build the full LookML tree but mark the excluded explores as such. That way, we can assign all errors to their relevant explores, assign dangling errors to the relevant model, and then only return the errors for the explores that weren't marked as excluded and the top-level model errors.

@joshtemple, would love your take on all of this.

**Comment by joshtemple** [comment]
I think that approach makes sense. You do your best to assign errors to whatever level of the LookML tree you can: explore, model, or fully orphaned. Then you only return errors from the part of the tree that matches selection/exclusion criteria + any fully orphaned errors.
