### ISSUE TITLE
Run data tests as different user with sudo

### ISSUE THREAD

**Issue by joshuasimon-taulia** [spectacles-ci/spectacles#295]
Hi,

We are using looker `access_filters` in our models to limit the data that each user sees based upon a user attribute. We'd like to use looker data tests to validate that our `access_filter` is functioning correctly. Let's say that i generate some fixture looker users at CI time with various values for the `user attribute`. Can spectacles use the sudo functionality in the looker api to run data tests as a particular user?

I'm also totally open to a different way to test `access_filter` if you have any experience here.

**Comment by joshtemple** [comment]
Hey @joshuasimon-taulia! We don't have any way to sudo as other Looker users in Spectacles. However, if you're generating fixture users anyway, you could set their user attributes, then authenticate as them in Spectacles using their own client IDs and secrets.

If you're doing this via the API, it might be challenging because AFAIK there's no way to get a generated client secret, so you might have to set these users up in the Looker UI beforehand.

Are the data tests to verify that a given user _can_ see certain data or to that they _can't_ see certain data?

**Comment by joshuasimon-taulia** [comment]
Yeah, generating api keys is a pain atm.

> Are the data tests to verify that a given user can see certain data or to that they can't see certain data?

The data tests in question would verify that a particular customer can't see another customer's data.

**Comment by joshtemple** [comment]
Could you use a single, pre-created user, but change their user attribute via the API during testing in CI?

Out of curiosity, how are you verifying inability to see data through a data test?

**Comment by joshuasimon-taulia** [comment]
> Could you use a single, pre-created user, but change their user attribute via the API during testing in CI?

Yes, that could work.

> Out of curiosity, how are you verifying inability to see data through a data test?
probably something along the lines of
```
test: customer_x_can_only_see_customer_x_records {
  explore_source: my_explore_used_by_all_customer_dashboards {
    column: count {
      field: invoice_details.count
    }
  }
  assert: customer_x_can_only_see_customer_x_records {
    expression: ${invoice_details.count} == $HARD_CODED_NUMBER_BASED_ON_FIXTURE_DATA ;;
  }
}

```

**Comment by joshtemple** [comment]
Hey @joshuasimon-taulia! I'm going to close this issue, since it seems like there are options for a workaround and since I don't see sudoing as a widely needed feature for Spectacles users.
