### ISSUE TITLE
SQL Test hangs

### ISSUE THREAD

**Issue by leoch20** [spectacles-ci/spectacles#492]
Hello, one of our modes has a large sql test which takes too long to run. When I take sql query that's run against the database and remove the everything under the `group by` clause, the query runs in a few seconds.
Is there a way to simplify the test query to avoid this issue?

**Comment by joshtemple** [comment]
Hi @leoch20, I'm guessing you're on Snowflake?

**Comment by leoch20** [comment]
Yes sir!

**Comment by joshtemple** [comment]
Yeah, we encounter this issue with Snowflake a lot. Basically, Snowflake's query planner gets bogged down when you have something like `GROUP BY 1,2..345,346`. We've written up [a guide here](https://gist.github.com/DylanBaker/72b78d4302bd8480b12a475e09e1e79b) for how we recommend resolving this using Looker's `cancel_grouping_fields`.

It's not a perfect solution—we'd love to get this resolved by Snowflake directly instead of workarounds, so if you have a relationship with Snowflake and can file a bug report, we'd always appreciate some noise being made so this can get be fixed.

**Comment by leoch20** [comment]
Thanks for the info. I will take a look at the guide and raise a ticket with Snowflake!
