### ISSUE TITLE
[Doc] Should `branch`, `commit_ref`, `project` and `remote-reset` place on global flags page?

### ISSUE THREAD

**Issue by Shumpei-Kikuta** [spectacles-ci/spectacles#550]
Thank for your work!
Spectacles is really helpful for detecting the lookml error and enhancing the lookml code quality.

I read through the document and I found `branch`, `commit_ref`, `project` and `remote-reset` on each validator section: SQL, Content, Assert and LooML Validation.
https://docs.spectacles.dev/cli/reference/sql-validator

These options should be set globally, and it would be clearer to place these options on global flags page.
https://docs.spectacles.dev/cli/reference/global-flags

If this proposal is right for you, I want to make a pull request.
Is Spectacles document open to commit? I cannot find the repository of the document.

Thank you for consideration!

**Comment by DylanBaker** [comment]
Hi @Shumpei-Kikuta. Thanks for your message!

I believe the reason we don't have them on the global flags is because they technically don't work with the `connect` command in Spectacles. That said, we don't have a reference page for `connect`, which we should probably add.

Unfortunately, our docs are currently not open-source. We might decide to do so in the future, but for the moment this is the best place to recommend/request changes.

**Comment by joshtemple** [comment]
While I agree we should document the `connect` command, I agree with @Shumpei-Kikuta that it would make more sense to move all of these things to global flags. For typical Spectacles usage, these are global options. I would rather the `connect` command be an exception rather than the rule.

**Comment by joshtemple** [comment]
I've opened a corresponding issue on our internal docs repo so we can get this resolved.

**Comment by Shumpei-Kikuta** [comment]
Thank you @joshtemple .
I hope this change makes the document easier to understand !
