### ISSUE TITLE
Spectacles fails when doing use `--incremental` and there's a new explore

### ISSUE THREAD

**Issue by friendofasquid** [spectacles-ci/spectacles#708]
Our Spectacles invocation looks like this:

`spectacles sql --concurrency 24 --verbose --incremental`

In this case, when we have a new explore in the branch under test (we are passing branch via environment variable `LOOKER_GIT_BRANCH`), Spectacles fails as follows:

```
The connection pool was closed while 17 HTTP requests/responses were still in-flight.
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/spectacles/client.py", line 659, in get_lookml_dimensions
    response.raise_for_status()
  File "/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/httpx/_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '404 Not Found' for url 'https://foo.cloud.looker.com/api/4.0/lookml_models/my_model/explores/fct_subscription_canceled?fields=fields'
For more information check: https://httpstatuses.com/404
```

I'd expect the behaviour to be the any 404s triggered against the production branch, but not against the branch under test, would just be flagged as an "incremental" error, not cause Spectacles to exception.

**Comment by DylanBaker** [comment]
Hey @friendofasquid. Thanks for the bug report. Would you mind sharing which version of Spectacles you're using? Thanks!

**Comment by friendofasquid** [comment]
Sure!

Looks like today, we saw it on 2.3.10. Pretty sure I saw this yesterday or the day before on 2.3.9.

**Comment by DylanBaker** [comment]
Thanks. And is the new explore in an existing model or was a new model created?

**Comment by friendofasquid** [comment]
> Thanks. And is the new explore in an existing model or was a new model created?

A new explore in an existing model. So it looks like when it's trying to hit that explore on the production branch, it's rightly getting a 404.

**Comment by DylanBaker** [comment]
@friendofasquid I've tried to replicate this and can't seem to do so unfortunately. 

On each state, we rebuild the project and then only find dimensions for models/explores that we find on that branch/state. When I test this with a new explore, it seems to function correctly for me. 

Would you mind sending the full logs from a run where this happens? You can either do that with the `-v` flag or check the `logs/` directory.

Additionally, I noticed you're not running your command with [the `--remote-reset` flag](https://docs.spectacles.dev/cli/reference/sql-validator/#remote-reset). In theory, this shouldn't cause this error as far as I can tell but maybe something funky is happening because an older state of the tested branch is being pulled. Would you mind re-running with that flag to see if it persists as well? Thanks!

**Comment by friendofasquid** [comment]
Thanks for trying. I'll need to wait until we see this again and report. back. Might be a while.

Is the code supposed to hit that Looker endpoint on the main branch, and handle it gracefully if it 404s? If you can reproduce, perhaps Looker's API responses are differing slightly. All pure speculation at this point.

**Comment by DylanBaker** [comment]
It's not supposed to hit any explores that don't exist in that state. It "builds" the models and explores in each git state before going to get the dimensions, which is why this error is a little confusing.

Do you ever have multiple Spectacles runs happening simultaneously with the same Looker creds?

**Comment by friendofasquid** [comment]
> Do you ever have multiple Spectacles runs happening simultaneously with the same Looker creds?

Yes, it certainly has happened, but we got this error with no concurrency. 

This was all during my first day or two setting this up, so it was all a bit new to me.
