### ISSUE TITLE
Mocking Looker's API

### ISSUE THREAD

**Issue by DylanBaker** [spectacles-ci/spectacles#8]
As I was writing the code to mock the Looker API, I had two thoughts:

1. it is likely to add a lot of code to the Fonz codebase,
2. it is probably useful for other things we work on as a separate service. (I could have really used it for `lookeraccess`.

I think we should leave it in Fonz for the moment as we flesh out the structure of the mock, but wanted to create an issue to start discussing whether we should ultimately split it into a different service that we simply import here for testing.

**Comment by DylanBaker** [comment]
Also, I tried to figure out if there's a way to auto-generate a mock with `swagger-stub` but I couldn't figure it out...

**Comment by joshtemple** [comment]
I think this is generally a good idea, but let's not rely on mocking _too_ much.

I found this at the bottom of Looker's [API Versioning page](https://docs.looker.com/reference/api-and-integration/api-versioning).
>In all cases, the best practice is to have unit tests that exercise your application code, including calls to the Looker API (not mocked calls).

Since we'll be using a ton of beta endpoints and since Looker seems to be doing a lot of active development on the API, we'll need to make sure we're repeatedly checking our assumptions about how the API works.

Agree with you: let's leave it here for now and consider splitting it out once we've demonstrated the value and have more coverage.

**Comment by DylanBaker** [comment]
Oh, interesting. I, for probably incorrect reasons, was under the impression that you should be able to test your software on a self-contained basis. 

Should we re-work the tests to actually take info from a Looker instance? How do we ensure that the data from the instance stays static?

**Comment by joshtemple** [comment]
You're totally right, we should still be mocking and testing everything with assumptions of how we think the API is responding. I didn't mean to suggest we should stop work on that front.

In addition, we should have some speedy tests that we run to confirm the endpoints we use are responding according to our assumptions. These could be a part of our CI pipeline, or something we run occasionally manually. We should also sign up for anything Looker publishes related to development of their API so we're aware.
