### ISSUE TITLE
Be able to specify which view you want to test

### ISSUE THREAD

**Issue by DylanBaker** [spectacles-ci/spectacles#92]
Currently, you can specify which models and/or explores that you want spectacles to test.

If you are doing LookML development, you are probably more aware of which view you are changing and not every explore that it is part of. (In fact, I think part of the whole idea here is that you shouldn't have to know everywhere your changes are being used.)

I think it's possible this will extend to a dimensions argument, as again, you would probably want to specify it relative to a view, not an explore?

**Comment by joetopp** [comment]
+1 to this. It would also be cool to specify views you _dont_ want to test. For example, If you've got a paramterized PDT, you're not going to want to test any of the associated dimensions because they'll always fail.

 A nice implementation might be regex-based `--include <dimension_regex>` and `--exclude <dimension_regex>` arguments?
